feature: is_filesystem and is_process variables added to determine current execution context.
binalyze/gora pull request #7
Opened 2023-04-14 12:05 UTC by asalih

2023-04-14 12:46 UTC, ozanh requested changes
Hi Ahmet,

We can remove `Ctx` suffix from isProcessCtx and isFileSystemCtx and related methods. It is misleading if you have context.Context around.

We haven't used `is_`prefix for other bool variables; we shouldn't use it for these as well, right?

Lastly, the variable names should be the same as the doc. comment.

2023-04-14 13:52 UTC, asalih commented
hello ab, imo if I remove is_ prefix then there will be only filesystem and process left which might be more general naming and difficult to understand.

2023-04-14 14:05 UTC, asalih commented
@ozanh updated with better naming thank you abi

2023-04-17 14:44 UTC, ozanh approved these changes

2023-04-17 14:45 UTC, merged